### ISSUE TITLE
`Es2022Intl` causes panic

### ISSUE THREAD

**Issue by togami2864** [dudykr/stc#530]
Part of #467 

While analyticing builtin`Es2021Intl`, `stc` fails to get `Symbol` type from global values. So, `[Symbol.iterator]` in `SegmentData` panics.
https://github.com/dudykr/stc/blob/9303105218af1610c69f4e1c5800bb216280523c/crates/stc_ts_builtin_types/lib/es2022.intl.d.ts#L32-L42

Log: run `./scripts/test.sh privateNameFieldsESNext`
```
~~~
  DEBUG  Analyzer.find_type('SegmentData#0')
    at crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs:1758
    in Scope::find_type with name: SegmentData#0
    in Scope::find_type with name: SegmentData#0
    in Scope::find_type with name: SegmentData#0
    in find_local_type
    in find_type with name: SegmentData#0
    in Stmt with line_col: ""

   INFO  (2) type_of_raw_var(Symbol#0)
    at crates/stc_ts_file_analyzer/src/analyzer/expr/mod.rs:3363
    in type_of_var
    in validate_key
    in Stmt with line_col: ""

  DEBUG  (2) Analyzer.find_type(`Symbol#0`)
    at crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs:1126
    in find_local_type
    in find_type with name: Symbol#0
    in type_of_var
    in validate_key
    in Stmt with line_col: ""

  DEBUG  Analyzer.find_type('Symbol#0')
    at crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs:1758
    in Scope::find_type with name: Symbol#0
    in find_local_type
    in find_type with name: Symbol#0
    in type_of_var
    in validate_key
    in Stmt with line_col: ""

  DEBUG  Analyzer.find_type('Symbol#0')
    at crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs:1758
    in Scope::find_type with name: Symbol#0
    in Scope::find_type with name: Symbol#0
    in find_local_type
    in find_type with name: Symbol#0
    in type_of_var
    in validate_key
    in Stmt with line_col: ""

  DEBUG  Analyzer.find_type('Symbol#0')
    at crates/stc_ts_file_analyzer/src/analyzer/scope/mod.rs:1758
    in Scope::find_type with name: Symbol#0
    in Scope::find_type with name: Symbol#0
    in Scope::find_type with name: Symbol#0
    in find_local_type
    in find_type with name: Symbol#0
    in type_of_var
    in validate_key
    in Stmt with line_col: ""

thread 'conformance::classes::members::privateNames::privateNameFieldsESNext.ts' panicked at 'internal error: entered unreachable code: builtin error: NoSuchVar { span: Span { lo: BytePos(0), hi: BytePos(0), ctxt: #0 }, name: Symbol#0 }', crates/stc_ts_storage/src/lib.rs:397:9
stack backtrace:
~~~
```

## Reproduction
1. enable `Es2022Intl`

https://github.com/dudykr/stc/blob/9303105218af1610c69f4e1c5800bb216280523c/crates/stc_ts_builtin_types/lib/es2022.d.ts#L4

2. run check.sh
3. A lot of files panic

**Comment by kdy1** [comment]
I expect this to be fixed by https://github.com/dudykr/stc/issues/530

**Comment by togami2864** [comment]
(Isn't it around #550??)
All tests are working well on the latest branch🎉

**Comment by kdy1** [comment]
My mistake 🤣
